pub mod config;
pub mod download;
pub mod engine;
pub mod error;
pub mod mock;
pub mod ollama;
pub mod onnx;
pub mod openai_compatible;
pub mod provider;
pub mod utils;

pub use config::{EmbeddingConfig, OnnxEmbeddingConfig};
pub use download::{ModelUrls, download_model, ensure_model_exists, ensure_tokenizer_exists};
pub use engine::EmbeddingEngine;
pub use error::{EmbeddingError, EmbeddingResult};
pub use mock::MockEmbeddingEngine;
pub use ollama::OllamaEmbeddingEngine;
pub use onnx::OnnxEmbeddingEngine;
pub use openai_compatible::OpenAICompatibleEmbeddingEngine;
pub use provider::EmbeddingProvider;
pub use utils::{handle_embedding_response, is_embeddable, sanitize_embedding_inputs};
