//! stdio MCP adapter for Cognee's Minimal Memory API.

pub mod atomic_fs;
pub mod cli;
pub mod config;
#[cfg(feature = "runtime")]
pub mod context;
#[cfg(feature = "runtime")]
pub mod detach;
pub mod diagnostic;
#[cfg(feature = "engine")]
pub mod drain;
pub mod embedding_generation;
pub mod engine;
pub mod error;
pub mod event;
pub mod generation;
#[cfg(feature = "runtime")]
pub mod hook;
pub mod hook_input;
pub mod layout;
#[cfg(feature = "runtime")]
pub mod lease;
#[cfg(feature = "runtime")]
pub mod ledger;
pub mod limits;
#[cfg(feature = "runtime")]
pub mod mcp;
pub mod protocol;
pub mod redact;
pub mod reference;
#[cfg(feature = "runtime")]
pub mod scheduler;
pub mod secret;
pub mod spool;
#[cfg(feature = "runtime")]
pub mod stdio;
#[cfg(feature = "runtime")]
pub mod tools;
#[cfg(feature = "runtime")]
pub mod worker;
